// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_owenk7.Models;

namespace Mission06_owenk7.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230214005732_Movies")]
    partial class Movies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_owenk7.Models.FormModel", b =>
                {
                    b.Property<int>("movieid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movieid");

                    b.ToTable("recommendations");

                    b.HasData(
                        new
                        {
                            movieid = 1,
                            cat = "Action/Adventure",
                            director = "John McTiernan",
                            edited = false,
                            rating = "R",
                            title = "Die Hard",
                            year = 1988
                        },
                        new
                        {
                            movieid = 2,
                            cat = "Action/Adventure",
                            director = "Renny Harlin",
                            edited = false,
                            rating = "R",
                            title = "Die Hard 2",
                            year = 1990
                        },
                        new
                        {
                            movieid = 3,
                            cat = "Family",
                            director = "Jennifer Lee, Chris Buck",
                            edited = true,
                            rating = "PG",
                            title = "Frozen 2",
                            year = 2019
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
